### ISSUE TITLE
infoFile not recognized

### ISSUE THREAD

**Issue by samuelail** [malczak/flag-icon-swift#1]
Hi, I am using :   

if let flagSheet = FlagIcons.loadSheetFrom(infoFile) {
            let image = flagSheet.getImageFor("PL")
            
        }

but this definitely throws an error just by looking at is because "infoFile" is not recognized.  What is supposed to be in place of that?

**Comment by malczak** [comment]
Thanks for your interest, please see updated README and usage sample app
